### PR TITLE
chore(mlx-lm): refactor server.py to utilize generate_step from utils for consistency

### PR DESCRIPTION
**Pull request by mzbac**
Address the comment from https://github.com/ml-explore/mlx-examples/pull/486

### CODE REVIEW

**Comment by mzbac** [comment]
@awni I tested the repetition penalty from my local machine, and it seems to be working fine. The PR is ready for review, please let me know if anything else needs to be changed.

**Comment by awni** [comment]
Thanks @mzbac . Should we also remove the `generate` function in `serer.py`? It is unused right?

**Comment by mzbac** [comment]
Yeah, sorry my bad. I forgot to delete it. I will update it.

**Review by awni — APPROVED** [review]
Awesome, thanks!!

**Pull request merged**
