### PR TITLE
Add support for Llama-3.1 

### PR DESCRIPTION
**Pull request by Blaizzy**
Add custom dynamic scaling for llama 3.1

### CODE REVIEW

**Comment by Blaizzy** [comment]
Still WIP, currently testing it

**Comment by Blaizzy** [comment]
@awni Today is my birthday so I'm OoO :) 

It appears to me that this needs more attention.

You could either take over and wait till I get back tomorrow.

**Comment by Blaizzy** [comment]
@AlexCheema this should work upto 8K context.

I will have to run some tests tomorrow for 128K.

**Comment by Blaizzy** [comment]
I will finish the rest of testing tomorrow.

**Comment by awni** [comment]
Closing in favor of #907

**Pull request closed without merging**
