### PR TITLE
Add workaround for apply_chat_template on server.py

### PR DESCRIPTION
**Pull request by alwint3r**
This PR is a workaround for the issue related to the transformers library as described in issue #647.

### CODE REVIEW

**Comment by mzbac** [comment]
After reading the documentation [here](https://huggingface.co/docs/transformers/main/chat_templating#what-template-should-i-use), it appears that disabling add_special_tokens is intentional. Based on the documentation, it seems like we should address this issue in the chat template.

**Comment by mzbac** [comment]
I just double-checked on my local and found that updating the chat_template in tokenizer_config.json to `"chat_template": "{% if not add_generation_prompt is defined %}{% set add_generation_prompt = false %}{% endif %}+'<s>'+{% for message in messages %}{{'<|im_start|>' + message['role'] + '\n' + message['content'] + '<|im_end|>' + '\n'}}{% endfor %}{% if add_generation_prompt %}{{ '<|im_start|>assistant\n' }}{% endif %}"` fixed the issue as well.

**Comment by alwint3r** [comment]
Interesting! Adding the `<s>` before the messages fixed the issue. Thanks @mzbac, I'll close the issue and PR for now.

**Comment by mzbac** [comment]
> Interesting! Adding the `<s>` before the messages fixed the issue. Thanks @mzbac, I'll close the issue and PR for now.

Apologies for leading you in the wrong direction. I didn't know that Transformers prefer handling special characters in chat templates over the tokenizer.

**Comment by alwint3r** [comment]
> > Interesting! Adding the `<s>` before the messages fixed the issue. Thanks @mzbac, I'll close the issue and PR for now.
> 
> Apologies for leading you in the wrong direction. I didn't know that Transformers prefer handling special characters in chat templates over the tokenizer.

No worries @mzbac. Thanks for the help.

**Pull request closed without merging**
