### PR TITLE
Adding support for mamba

### PR DESCRIPTION
**Pull request by Goekdeniz-Guelmez**

### CODE REVIEW

**Comment by awni** [comment]
Awesome! Does it work yet?

**Comment by Goekdeniz-Guelmez** [comment]
> Awesome! Does it work yet?

Almost, I can create and generate with the sead created model but still have some issues loading a pretrained one. The problem arises from the Conv1D layer, it expects shape [a, b, a] but gets [a, b, c]. I'll give you the original error, later.

**Comment by Goekdeniz-Guelmez** [comment]
> > Awesome! Does it work yet?
> 
> Almost, I can create and generate with the sead created model but still have some issues loading a pretrained one. The problem arises from the Conv1D layer, it expects shape [a, b, a] but gets [a, b, c]. I'll give you the original error later, when im on my mac.

i found the problem. No i have that error: `ValueError: [transpose] Recived 2 axes for array with 3 dimensions.` in the call method:

```
    def __call__(self, x, cache=None):
        # x : (B, L, D)

        # y : (B, L, D)

        _, L, _ = x.shape

        # xz = self.in_proj(x) #/ (B, L, 2*ED)
        x, z = self.in_proj(x).split(indices_or_sections=2, axis=2) # (B, L, ED), (B, L, ED)

        # x branch
        x = self.conv1d(x.transpose(1, 2)).transpose(1, 2)[:, :L, :] # depthwise convolution over time, with a short filter

        x = nn.silu(x)
        y = self.ssm(x)

        output = y * nn.silu(z)
        output = self.out_proj(output) # (B, L, D)

        return output, cache
```

**Comment by Goekdeniz-Guelmez** [comment]
Update!!!

The loading problem is fixed but I now get this error in inference:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/gokdenizgulmez/Desktop/mlx-examples-drafts/llms/mlx_lm/generate.py", line 161, in <module>
    main()
  File "/Users/gokdenizgulmez/Desktop/mlx-examples-drafts/llms/mlx_lm/generate.py", line 148, in main
    generate(
  File "/Users/gokdenizgulmez/Desktop/mlx-examples-drafts/llms/mlx_lm/utils.py", line 315, in generate
    for (token, logprobs), n in zip(
  File "/Users/gokdenizgulmez/Desktop/mlx-examples-drafts/llms/mlx_lm/utils.py", line 220, in generate_step
    y, logprobs = model.generate_step(prompt)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gokdenizgulmez/Desktop/mlx-examples-drafts/llms/mlx_lm/models/mamba.py", line 371, in generate_step
    next_token_logits, caches = self(input_ids, caches)
                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gokdenizgulmez/Desktop/mlx-examples-drafts/llms/mlx_lm/models/mamba.py", line 314, in __call__
    out, cache = self.backbone(inputs, cache)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gokdenizgulmez/Desktop/mlx-examples-drafts/llms/mlx_lm/models/mamba.py", line 301, in __call__
    h, cache[i] = layer(tokens, cache[i])
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gokdenizgulmez/Desktop/mlx-examples-drafts/llms/mlx_lm/models/mamba.py", line 286, in __call__
    output, cache = self.mixer(self.norm(inputs), cache)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gokdenizgulmez/Desktop/mlx-examples-drafts/llms/mlx_lm/models/mamba.py", line 271, in __call__
    x = self.conv1d(mx.concatenate([inputs, x_cache], axis=1))[:, self.conv_kernel_size-1, :]
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: [concatenate] All the input arrays must have the same number of dimensions. However, got arrays with dimensions 3 and 4.
```

**Pull request closed without merging**
