### PR TITLE
Starcoder2: Update config and change GQA to use repeat

### PR DESCRIPTION
**Pull request by Blaizzy**
This PR updates the config to match the HF Starcoder config and changes GQA to use repeat instead of concatenate as suggested here https://github.com/ml-explore/mlx-examples/pull/443. 

@mzbac the PR is ready!
https://github.com/ml-explore/mlx-examples/pull/502#issuecomment-1975063865

### CODE REVIEW

**Comment by Blaizzy** [comment]
@mzbac let me know if there are any further changes need.

**Comment by mzbac** [comment]
Looks good to me. Let's see if @awni could help review and approve it :)

**Comment by Blaizzy** [comment]
Awesome!

**Review by awni — APPROVED** [review]
LGTM, thanks!!

**Pull request merged**
