### PR TITLE
Gemma support

### PR DESCRIPTION
**Pull request by awni**
Add support for gemma model type:

Should run with:

python -m mlx_lm.generate --model google/gemma-7b-it --prompt "Write a quick sort in C++"

### CODE REVIEW

**Comment by Solido** [comment]
Can we already qlora it with mlx?

**Comment by awni** [comment]
Oh yea that should work fine! I just added it to the allowed LoRA models.

**Review by angeloskath — APPROVED** [review]
🚀

**Comment by Solido** [comment]
I'm impress, this landed minutes after the official release.
Right now I'm working with the examples/lora but there's also mlx-llm.
Both dir have specific conf for llama, phi, etc but I cannot see update for gemma.
What's is the up to date way to train? is lora deprecated? 
Thank you!

**Comment by ngbinh** [comment]
awesome!

**Review by lazarust — APPROVED** [review]
LGTM!

**Comment by awni** [comment]
@Solido 

The `lora/` example is not deprecated. It's just not being extended to be more fully featured. It is mostly used as an educational example and/or starting point for someone wanting to extend.

To use all the bells and whistles, use `mlx_lm.lora` : https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/LORA.md

**Comment by Solido** [comment]
@awni I'm on master, last commit, running

`python3 -m mlx_lm.lora --model google/gemma-2b-it --train --iters 200 --resume-adapter-file ./adapters.npz`

_ValueError: Model type gemma not supported._

**Comment by awni** [comment]
Sorry I might have messed that up, let me check!

**Comment by awni** [comment]
@Solido it works find for me:

```
python -m mlx_lm.lora --model google/gemma-7b-it --train --data ../lora/data 
Loading pretrained model
Fetching 11 files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 11/11 [00:00<00:00, 45862.17it/s]
Total parameters 8539.516M
Trainable parameters 1.835M
Loading datasets
Training
Starting training..., iters: 1000
Iter 1: Val loss 9.731, Val took 15.371s
Iter 10: Train loss 8.709, Learning Rate 1.000e-05, It/sec 0.734, Tokens/sec 272.181, Trained Tokens 3708
```

**Comment by awni** [comment]
Maybe you need to uninstall `mlx_lm` and reinstall (or force update):

`pip install -U mlx-lm`

**Comment by Solido** [comment]
This was it! thank you very much for mlx, even dev like me can be on track with such a tool!

**Comment by seshakiran** [comment]
This was fast...and crazy. I got this up and running on my Mac. Amazing!

**Comment by fblissjr** [comment]
Has anyone had any success instruction tuning the base gemma models via the mlx_lm lora? Curious if it's worth trying.

**Comment by siddartha-10** [comment]
@awni I am having same problem @Solido ```bash ValueError: Model type gemma not supported.```

**Comment by awni** [comment]
What are you running? Share the command?

**Comment by siddartha-10** [comment]
```
python3 lora.py \
  --train \
  --model google/gemma-2b-it \
  --data ~/Fine-tuning/data \
  --adapter-file ~Fine-tuning/adapters_file \
  --batch-size 2 \
  --lora-layers 4 \
  --iters 200```

**Comment by awni** [comment]
Ah you should use the mlx LM Lora https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/LORA.md

**Comment by siddartha-10** [comment]
Thanks for the response,  it's working now.

**Comment by siddartha-10** [comment]
@awni I think the code used for generating from the fine-tuned model using adapters.npz is missing from the doc?
```https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/LORA.md#Generate```

and i am not sure how to do it.

**Comment by awni** [comment]
Would you mind filling an issue or asking in a discussion? I am happy to help but I will lose track if it’s in this PR

**Comment by siddartha-10** [comment]
Sure, i will create an issue.

**Pull request merged**
