### PR TITLE
Fix for cohere plus

### PR DESCRIPTION
**Pull request by awni**
Use the qk norm param to work with cohere plus.

Machine setting:

```
sudo sysctl iogpu.wired_lwm_mb=100000
```

Command for generation:

```
python -m mlx_lm.generate --model mlx-community/c4ai-command-r-plus-4bit --prompt "Write a quicksort in c++" --temp 0.0 --max-tokens 256 --use-default-chat-template
```

Command for QLoRA:

```
python -m mlx_lm.lora --model mlx-community/c4ai-command-r-plus-4bit --data ../lora/data --train --iters 1000  --batch-size 1 --lora-layers 16
```

### CODE REVIEW

**Comment by Blaizzy** [comment]
I was about to submit a PR, great I checked 😄.

**Comment by DenisSergeevitch** [comment]
@Blaizzy Thank you! How much RAM does it require to run 4bit q?

**Comment by awni** [comment]
Needs about 65GB to generate with 4-bit. But the generation is slow right now, trying to debug the performance issue.

**Comment by Blaizzy** [comment]
> @Blaizzy Thank you! How much RAM does it require to run 4bit q?

As @awni said 👆🏽

I can't run it myself, I use a M1 Air 16GB :)

**Comment by DenisSergeevitch** [comment]
Thank you, I will wait for i_q1 then

**Comment by awni** [comment]
Btw to get this to run reasonably fast on an M2 Ultra you need to set the wired GPU memory limit appropriately. Something like:

```
sudo sysctl iogpu.wired_lwm_mb=100000
```

**Review by angeloskath — APPROVED** [review]
Thanks!

**Comment by jeanromainroy** [comment]
I am running the 4-bit version of Command-R-Plus and I consistently see the GPU usage dropping during generation and performance becoming abysmal. 

Screenshot 2024-04-08 at 10 10 21 PM


My machine is the M2 Ultra 192GB and,

ProductName:		macOS
ProductVersion:		14.3
BuildVersion:		        23D56

**Comment by Blaizzy** [comment]
@awni 👆🏽

**Comment by awni** [comment]
@jeanromainroy did you set the memory limits? You could try making it larger:

```
sudo sysctl iogpu.wired_lwm_mb=150000
``

**Comment by jeanromainroy** [comment]
Even after setting this,

`sudo sysctl iogpu.wired_lwm_mb=150000`

I still see the GPU usage dropping.

Screenshot 2024-04-09 at 12 34 55 PM

**Comment by awni** [comment]
Do you mind to open an issue and include the command, versions of MLX / MLX LM, OS etc?

**Pull request merged**
