### PR TITLE
feat: add chronos model

### LINKED ISSUE #587: Add chronos model(s) to mlx-lm
I would like to add the chronos model(s). Looking for feedback or suggestion from the maintainers.

- paper: https://arxiv.org/abs/2403.07815
- model: https://huggingface.co/amazon/chronos-t5-large

### PR DESCRIPTION
**Pull request by sugatoray**
- [x] Implementation Plan:
  - [ ] implement torch to mlx
  - [ ] discuss current implementation with maintainers
  - [ ] make updates based on review suggestions
  - [ ] test code end-to-end 
- [ ] clean up comments after final run (pre-merge)

Closes #587

### CODE REVIEW

**Comment by sugatoray** [comment]
cc: @awni @mzbac

**Comment by abdulfatir** [comment]
@sugatoray thanks for opening this! I was also working on this on our side. Happy to review once this is ready.

**Comment by sugatoray** [comment]
@abdulfatir That's great! 🎉 If it's okay with you, I am open to collaborate.

**Comment by abdulfatir** [comment]
Sure, I can share a more-or-less working implementation in a bit. Maybe you can build upon that? A couple of things to note about the current T5 implementation in this repo:
- When embeddings are tied (which is the case for Chronos), the scaling is incorrect: #591 
- It doesn't support attention_mask which would cause problems for time series that are too shot.

**Comment by abdulfatir** [comment]
@sugatoray sharing some files that may help you move forward.

[chronos-mlx.zip](https://github.com/ml-explore/mlx-examples/files/14625068/chronos-mlx.zip)

A few things to note:

- I didn't remove/modify the docstrings, so please modify them as required.
- I didn't implement `top_p` sampling. Please feel free to implement that or remove the option.

Here's a script that I used to benchmark the speedup.

```py
import timeit

import torch
from chronos import ChronosPipeline as ChronosPipelineTorch
from gluonts.dataset.repository import get_dataset
from gluonts.dataset.split import split
from gluonts.ev.metrics import MASE
from gluonts.model.evaluation import evaluate_forecasts
from gluonts.model.forecast import SampleForecast

from chronos_mlx import ChronosPipeline as ChronosPipelineMLX


def run_torch(test_data, prediction_length):
    print("Running torch version [CPU]:")

    start = timeit.default_timer()
    pipeline = ChronosPipelineTorch.from_pretrained(
        "amazon/chronos-t5-base", device_map="cpu", torch_dtype=torch.bfloat16
    )
    t1 = timeit.default_timer()
    print(f"\tModel load time: {t1 - start:.2f}s")
    forecasts = []
    for entry in test_data.input:
        forecast = pipeline.predict(
            torch.tensor(entry["target"]),
            prediction_length=prediction_length,
        )
        forecasts.append(
            SampleForecast(
                samples=forecast[0].numpy(),
                start_date=entry["start"] + len(entry["target"]),
            )
        )
    t2 = timeit.default_timer()
    print(f"\tInference time: {t2 - t1:.2f}s")

    metrics_df = evaluate_forecasts(forecasts, test_data=test_data, metrics=[MASE()])
    print(f"\tMASE[0.5]: {metrics_df['MASE[0.5]'].iloc[0].item():.3f}")
    return forecasts, metrics_df


def run_mlx(test_data, prediction_length):
    print("Running mlx version [M1 Pro]:")

    start = timeit.default_timer()
    pipeline = ChronosPipelineMLX.from_pretrained(
        "amazon/chronos-t5-base", dtype="bfloat16"
    )
    t1 = timeit.default_timer()
    print(f"\tModel load time: {t1 - start:.2f}s")
    forecasts = []
    for entry in test_data.input:
        forecast = pipeline.predict(
            entry["target"],
            prediction_length=prediction_length,
        )
        forecasts.append(
            SampleForecast(
                samples=forecast[0],
                start_date=entry["start"] + len(entry["target"]),
            )
        )
    t2 = timeit.default_timer()
    print(f"\tInference time: {t2 - t1:.2f}s")
    metrics_df = evaluate_forecasts(forecasts, test_data=test_data, metrics=[MASE()])
    print(f"\tMASE[0.5]: {metrics_df['MASE[0.5]'].iloc[0].item():.3f}")
    return forecasts, metrics_df


if __name__ == "__main__":
    dataset = get_dataset("australian_electricity_demand")
    prediction_length = 48
    _, test_template = split(dataset.test, offset=-prediction_length)
    test_data = test_template.generate_instances(prediction_length)
    run_torch(test_data, prediction_length)
    run_mlx(test_data, prediction_length)

```

and the output I got:
```
Running torch version [CPU]:
	Model load time: 0.76s
	Inference time: 99.73s
	MASE[0.5]: 1.386
Running mlx version [M1 Pro]:
	Model load time: 0.75s
	Inference time: 6.57s
	MASE[0.5]: 1.295
```

**Comment by sugatoray** [comment]
@abdulfatir This is great! Let me look at the code you shared and let's work on taking the best of both worlds. Thanks for sharing your work.

**Comment by awni** [comment]
This is super cool @sugatoray and thanks @abdulfatir for the input! 


I'm wondering what the right place for it is? It doesn't make much sense in MLX LM.. 

What about including an MLX implementation in the original repo? https://github.com/amazon-science/chronos-forecasting

**Comment by awni** [comment]
> What about including an MLX implementation in the original repo?

@sugatoray wdyt about that?

**Comment by sugatoray** [comment]
Hi @awni 

I will suggest we look at the final version and then take a call on where it will be more applicable to add the model. In principle, I am okay with both. 

However, I would appreciate if you could mention what types of models will be added to mlx-lm (aligning with the vision of the library), and what the criteria are to decide that. 

Last week and a half I was invested in something personal. Hopefully, I will be able to turn this in soon.

**Comment by awni** [comment]
> However, I would appreciate if you could mention what types of models will be added to mlx-lm (aligning with the vision of the library), and what the criteria are to decide that.

For now decoder-only language models for text generation.

**Comment by abdulfatir** [comment]
@awni @sugatoray I though this PR was for mlx-examples, not mlx-lm?

**Comment by sugatoray** [comment]
> @awni @sugatoray I though this PR was for mlx-examples, not mlx-lm?

@abdulfatir The models in the examples are mostly included in the mlx-lm library. That's what allows the community to install and convert various models on HF and allows for greater exposure and collaboration. 

If I am not mistaken, the models outside of mlx-lm were created first to provide guidance to the community in showing how to add models to mlx-lm.

**Comment by abdulfatir** [comment]
Ah, right! If mlx-lm is solely focused on text then maybe it makes sense to add it one level up, just like the other non-text examples? 
FYI, on adding MLX support to the main repo: we are discussing it but not sure yet. That repo is mainly supposed to be a companion for the paper and not something we plan to maintain, so we may not want to add too much complexity to it. I will let you know in case we decide to add it.

**Comment by awni** [comment]
Sounds good. This would indeed make more sense in mlx-examples but I’m not sure we would add there. I’d have to take a closer look but it might be too similar to T5 to merit the cost of an additional example.

I guess a third alternative is for @sugatoray to start a community lead repo which we would be happy to point people to.

**Comment by abdulfatir** [comment]
@sugatoray @awni I opened this issue in the main repo for discussion: https://github.com/amazon-science/chronos-forecasting/issues/28

**Pull request closed without merging**
