### PR TITLE
rename --model_path to --model-path

### PR DESCRIPTION
**Pull request by dastrobu**
use same argument convention for mistral/mixtral as for llama convert.

### CODE REVIEW

**Review by awni — APPROVED** [review]
Thank you! Consistency is a good thing 👍

**Comment by awni** [comment]
Is this PR intentionally in the draft state? I think it's good to go, but let me know if you were planning to add something!

**Comment by dastrobu** [comment]
> Is this PR intentionally in the draft state? I think it's good to go, but let me know if you were planning to add something!

@awni I just wanted to test it properly first. I did not find the time two days ago, but the PR should be fine. So it is ready to merge from my point of view now.

**Review by awni — APPROVED** [review]
Thanks for fixing it! This inconsistency was annoying.

**Pull request merged**
