### PR TITLE
Align CLI args and some smaller fixes

### PR DESCRIPTION
**Pull request by alvarobartt**
## Description

This PR is for aligning the args used within the CLI files to expose those in an uniform way to keep some sort of consistency within the files even some may be independent.

Additionally, while going through the examples some other minor fixes have been applied such as: removed unused imports, add missing type-hints, and some other minor fixes.

### CODE REVIEW

**Comment by dastrobu** [comment]
There is a PR aligning flags the other way around: #151 maybe the core maintainers should state what convention to follow.

**Comment by alvarobartt** [comment]
Oh fair, thanks @dastrobu! I'll keep the rest of the stuff but remove the CLI arg alignment, to me snake-case was more intuitive, but fair, maybe the other convention is preferred, thanks again!

**Comment by awni** [comment]
Thank you for your fixes! Lets go with `hyphen` for the model arguments (e.g. `--model-args`). The rest of the chnages look good. Let me know when this is ready to merge.

**Review by awni — APPROVED** [review]
Thanks!

**Comment by alvarobartt** [comment]
Sorry I couldn't follow up @awni I was off for some days, thanks for the comments! 👍🏻

**Comment by awni** [comment]
No worries, thanks for the contribution!

**Pull request merged**
