### PR TITLE
Fix Qwen2 moe

### PR DESCRIPTION
**Pull request by Blaizzy**
This PR fixes Qwen2 MoE conversion and inference.
Twitter: @Prince_Canuma

### CODE REVIEW

**Comment by awni** [comment]
This doesn’t look like the correct fix to me. We need to merge scales if they are there. Could you point to the model that didn’t work so we can debug?

**Comment by Blaizzy** [comment]
I could be wrong but from what I can see, both Qwen moe models don’t use scales. 

- https://huggingface.co/Qwen/Qwen1.5-MoE-A2.7B/tree/main
- https://huggingface.co/Qwen/Qwen2-57B-A14B-Instruct/tree/main

Precisely, the Qwen-2-57B-A14B model failed to convert.

**Comment by awni** [comment]
I do not have a problem converting `Qwen/Qwen2-57B-A14B-Instruct` on main. Can you share the error message you are getting?

**Comment by Blaizzy** [comment]
But they will be present in quantized models. I see it now. 

I will add a condition to skip scales for f16 or f32 models.

**Comment by Blaizzy** [comment]
> I do not have a problem converting `Qwen/Qwen2-57B-A14B-Instruct` on main. Can you share the error message you are getting?

Alright, give me a 15min to redownload the model.

> You don't need to add that, it will not try to use scales if they are not present already. See Line 228.

I noticed, and saw the git blame to trace the changes.
From what I can tell, the line above that (line 227)  is the one what is at fault :)

**Comment by Blaizzy** [comment]
That's weird, today is working fine.

Yesterday both pypi and github installation gave an error

An error exactly in line 228 where it said something about the first expert didn't have scales but I didn't save it anywhere.

**Pull request closed without merging**
