### PR TITLE
Make sure to import the correct "version" module when installing mlx_whisper and mlx_lm from local source code.

### PR DESCRIPTION
**Pull request by walkoncross**
Fix module conflicts when install mlx_whisper and mlx_lm from local source code.

## Problem

When installing mlx_whisper from local source code by running:
'''
cd whisper
pip install -e .
'''

I got an error as following:
'''
Obtaining file:///Users/zhaoyafei/work/mlx-examples/whisper
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/Users/zhaoyafei/work/mlx-examples/whisper/setup.py", line 15, in <module>
          from version import __version__
      ImportError: cannot import name '__version__' from 'version' (/Users/zhaoyafei/work/opendr/opendr/version.py)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
'''

The same error was encountered when installing the mlx_lm package from local source code.

### mlx-whisper
- Rename whisper/mlx_whisper/version.py into whisper/mlx_whisper/_version.py
- In whisper/setup.py, replace '''from version import __version__''' by '''from _version import __version__'''.

### mlx-lm
- Rename llms/mlx_lm/version.py into llms/mlx_lm/_version.py
- In llms/setup.py, replace '''from version import __version__''' by '''from _version import __version__'''.

### CODE REVIEW

**Comment by awni** [comment]
I'm not getting that error running `pip install -e .` in either subdirectory. And in fact the change you made would break other things (like building with `python -m build` so we should not do that.

Perhaps you need to upgrade pip? `pip install -U pip`. If that doesn't solve it.. please file an issue and we can help debug.

**Comment by walkoncross** [comment]
> I'm not getting that error running `pip install -e .` in either subdirectory. And in fact the change you made would break other things (like building with `python -m build` so we should not do that.
> 
> Perhaps you need to upgrade pip? `pip install -U pip`. If that doesn't solve it.. please file an issue and we can help debug.

I got this error because I have installed a python package (i.e opendr) which exposes a module named "version.py".  

I have tried "pip install -U pip." but it did not fix the error.

I have to manually fix the error everytime. 

This PR is just to avoid other people encountering similar problems.

**Comment by awni** [comment]
Gotcha! How about rename those files to _version.py?

**Comment by walkoncross** [comment]
> Gotcha! How about rename those files to _version.py?

@awni As long as it can solve the problem, it's fine.

**Comment by awni** [comment]
Do you want to update this PR with that change?

**Comment by walkoncross** [comment]
> Do you want to update this PR with that change?

@awni ok, I can do it.

**Comment by walkoncross** [comment]
> Fix module conflicts when install mlx_whisper and mlx_lm from local source code.
> 
> ## Problem
> When installing mlx_whisper from local source code by running: ''' cd whisper pip install -e . '''
> 
> I got an error as following: ''' Obtaining file:///Users/zhaoyafei/work/mlx-examples/whisper Preparing metadata (setup.py) ... error error: subprocess-exited-with-error
> 
> × python setup.py egg_info did not run successfully. │ exit code: 1 ╰─> [6 lines of output] Traceback (most recent call last): File "", line 2, in File "", line 34, in File "/Users/zhaoyafei/work/mlx-examples/whisper/setup.py", line 15, in from version import **version** ImportError: cannot import name '**version**' from 'version' (/Users/zhaoyafei/work/opendr/opendr/version.py) [end of output]
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. error: metadata-generation-failed
> 
> × Encountered error while generating package metadata. ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip. hint: See above for details. '''
> 
> The same error was encountered when installing the mlx_lm package from local source code.
> 
> ## Solution:
> ### mlx-whisper
> * Rename whisper/mlx_whisper/version.py into whisper/mlx_whisper/_version.py
> * In whisper/setup.py, replace '''from version import **version**''' by '''from _version import **version**'''.
> 
> ### mlx-lm
> * Rename llms/mlx_lm/version.py into llms/mlx_lm/_version.py
> * In llms/setup.py, replace '''from version import **version**''' by '''from _version import **version**'''.

@awni This PR has been updated according to the method we discussed.

**Review by awni — APPROVED** [review]
Thanks!

**Pull request merged**
