### PR TITLE
Switch to fast RMS/LN Norm

### PR DESCRIPTION
**Pull request by awni**
- Switch RMSNorm to `nn.RMSNorm` to get fast rms
- Switch LayerNorm to `nn.LayerNorm` to get fast LN
- Update a few more models to use SDPA
- Clean up old lora to reduce some surface area and point to MLX LM for more features.

NB tests won't clear until 0.8 is out, but they clear locally for me with latest MLX

### CODE REVIEW

**Review by angeloskath — APPROVED** [review]
🔥

**Comment by ivanfioravanti** [comment]
@awni  I noticed something strange, this started after this PR. Generation ois considerably slower when used with adapters file:

mlx 0.8 + mlx_lm 0.4 --> Prompt: 140.416 tokens-per-sec / **Generation: 24.049** tokens-per-sec
mlx 0.8 + mlx_examples https://github.com/ml-explore/mlx-examples/commit/5a52899405ee911ce07ca3132e781ce149acd6b5 --> Prompt: 106.642 tokens-per-sec / **Generation: 13.586 tokens-per-sec**
I use python -m mlx_lm.generate --model mistralai/Mistral-7B-v0.1 --max-tokens 300 --prompt "[INST] Discuss the pros and cons of genetically modified crops and their impact on the food industry and agriculture. [/INST]" --adapter-file ./adapters.npz

**Comment by awni** [comment]
That's odd and unexpected. Thanks for flagging, we'll take a look!

**Comment by awni** [comment]
Maybe we are inadvertently upcasting now when you include the adapters which would slow a lot of stuff down 🤔

**Pull request merged**
