### PR TITLE
mlx RAG with GGUF models example

### PR DESCRIPTION
**Pull request by Jaykef**
Minimal, clean code implementation of RAG with mlx inferencing for GGUF models.

The code here builds on https://github.com/vegaluisjose/mlx-rag, it has been optimized to support RAG-based inferencing for .gguf models. I am using [BAAI/bge-small-en](https://huggingface.co/BAAI/bge-small-en) for the embedding model, [TinyLlama-1.1B-Chat-v1.0-GGUF](https://huggingface.co/TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF/blob/main/tinyllama-1.1b-chat-v1.0.Q4_0.gguf) as base model and the custom vector database script for indexing texts in a pdf file. Inference speeds can go up to ~413 tokens/sec for prompts and ~36 tokens/sec for generation on my 8G M2 Air.

### CODE REVIEW

**Comment by awni** [comment]
Very cool!

I think this should live in a separate repo though (not MLX examples). Wdyt about starting one for it? Or maybe you can amend https://github.com/vegaluisjose/mlx-rag to include the GGUF support?

**Comment by Jaykef** [comment]
it already is https://github.com/Jaykef/mlx-rag-gguf, I just thought it might make sense to include it, but yeah you are right.

**Comment by awni** [comment]
Oh cool! Do you want to add it to our community projects page? https://github.com/ml-explore/mlx/discussions/654

**Comment by Jaykef** [comment]
yh that will be nice

**Pull request closed without merging**
