### PR TITLE
Fixes Typo in Starcoder2 Model

### PR DESCRIPTION
**Pull request by lazarust**

### CODE REVIEW

**Comment by lazarust** [comment]
Closes: #741

**Review by awni — APPROVED** [review]
Oops! Thanks!

**Comment by lazarust** [comment]
@awni Any idea when this would be released? I would like to convert https://huggingface.co/bigcode/starcoder2-15b-instruct-v0.1 since it was just released today.

**Comment by awni** [comment]
Just did a patch release `0.12.1` so you can use it.

**Comment by lazarust** [comment]
Thank you!!

**Pull request merged**
