### PR TITLE
Add epoch-based training support to lora.py

### PR DESCRIPTION
**Pull request by wyanzhao**
Adds epoch-based training functionality to lora.py. Previously, the script only allowed training iterations through manually specified iteration counts.

### CODE REVIEW

**Comment by madroidmaq** [comment]
@wyanzhao  It's basically updating the logic in `llms/mlx_lm/lora.py`, can you synchronize that part of the commit to the `llms/mlx_lm/lora.py` script.

**Comment by awni** [comment]
You can fork and update `lora/lora.py` as you like but won't merge these types of features into it with the intention of keeping it pretty simple.

If you have a change to trianing you could propose adding it to the LoRA functionality in MLX LM. If you're not sure, I encourage you to file an issue first!

**Comment by wyanzhao** [comment]
Hi folks, I've updated the code in llms/mlx_lm/lora.py based on the feedback provided. Please take a moment to review the updated code. Thanks for your valuable feedback.

**Comment by awni** [comment]
Hmm, I cannot reopen this PR. Can you reopen it?

**Comment by awni** [comment]
Actually now I can

**Pull request closed without merging**
