### PR TITLE
Phixtral

### PR DESCRIPTION
**Pull request by marcelbischoff**
Adding support for MoE models based on Phi-2 aka Phixtral 
- https://huggingface.co/mlabonne/phixtral-4x2_8
- https://huggingface.co/mlabonne/phixtral-2x2_8
This is an almost verbatim copy of the Phi-2 code and Mixtral MoE block

```sh
python llms/phixtral/generate.py --prompt "def fib(n: int) -> int:" \
--model mlabonne/phixtral-2x2_8
```

### CODE REVIEW

**Comment by awni** [comment]
Thanks for moving it. No rush, but you forgot to include the `phixtral.py` file 😄

**Comment by awni** [comment]
@marcelbischoff any reason this is draft? Should I go ahead and review it? (Also would be good to add a README, I can help with that if you like, lmk).

**Comment by marcelbischoff** [comment]
Hey, was mostly a draft because of missing README.

**Comment by marcelbischoff** [comment]
Should be ready to review

**Review by awni — APPROVED** [review]
Very nice, works well for me :)!!

**Pull request merged**
