### PR TITLE
Update server.py to add --trust-remote-code to server

### PR DESCRIPTION
**Pull request by sweetcard**
Add --trust-remote-code to server

### CODE REVIEW

**Review by Blaizzy — APPROVED** [review]
LGTM!

**Comment by Blaizzy** [comment]
@sweetcard can you run pre-commit ?

**Comment by sweetcard** [comment]
> @sweetcard can you run pre-commit ?

@Blaizzy Done and commit again. 
Please review again.

**Review by Blaizzy — APPROVED** [review]
LGTM ✅

**Review by awni — APPROVED** [review]
Thanks!! Will merge when the tests clear.

**Pull request merged**
