### PR TITLE
Add model management functionality for local caches

### PR DESCRIPTION
**Pull request by ivanfioravanti**
This commit introduces a set of command-line utilities for managing MLX models downloaded and saved locally in Hugging Face cache. The functionalities include scanning existing models, retrieving detailed information about a specific model, and deleting a model by its name.

This implements: #734

### CODE REVIEW

**Comment by fblissjr** [comment]
This is a really nice QOL improvement.

**Review by KE7 — APPROVED** [review]
Not necessary but cool to have.

**Comment by awni** [comment]
Awesome! I changed the API slightly to be a bit more flexible and changed the name from `mlx_lm.model` to `mlx_lm.manage` (model seems a bit to confusing with other models). Manage may not be great.. open to changing it if anyone has better ideas. Will merge for now though.

**Review by awni — APPROVED** [review]

**Comment by ivanfioravanti** [comment]
manage sounds better! It can be extended beyond models in future 🤔

**Pull request merged**
