### PR TITLE
Image classification with MLPMixer

### PR DESCRIPTION
**Pull request by gboduljak**
Added an example of image classification with `MLPMixer`.

Implemented: 
- [x] `MLPMixer` model
- [x] Preprocessing using `mlx-data`. 
- [x] Downloading and weight conversion using`convert.py`.
- [x] README.md

### CODE REVIEW

**Comment by awni** [comment]
This is super cool!

Nevertheless, I think it's slightly too niche for MLX examples. As a maintainer there is a tension between adding more examples which is great (!) versus our burden to maintain them / keep the repo manageable.

- What I would suggest is you make a standalone repo basically as is, and I would be happy to point people to it.
- In the future i hope we can have something like an MLX model zoo. And this would be a great fit for that.

PS if you are looking for more examples to include in MLX example, DM or start an issue. There are a few things that would be good to add still and I'm also happy to give some input on ideas.

**Comment by gboduljak** [comment]
> This is super cool!
> 
> Nevertheless, I think it's slightly too niche for MLX examples. As a maintainer there is a tension between adding more examples which is great (!) versus our burden to maintain them / keep the repo manageable.
> 
> * My suggestion is you make a standalone repo basically as is, and I would be happy to point people to it.
> * In the future i hope we can have something like an MLX model zoo. And this would be a great fit for that.
> 
> PS if you are looking for more examples to include in MLX examples, feel free to DM me or start an issue. There are a few things that would be good to add still and I'm also happy to give some input on ideas.

Makes sense :) This was relatively easy to implement so I did not start an issue before :)

**Comment by awni** [comment]
Will you put it in a standalone repo and send me the URL?

**Comment by gboduljak** [comment]
> Will you put it in a standalone repo and send me the URL?

I am thinking between a standalone repo or https://github.com/robertmccraith/mimm. Should we go for a standalone repo or should I contact the author of `mimm`? It seems that this model could fit there well.

**Comment by awni** [comment]
Ohh that's a nice idea! I don't know how actively @robertmccraith is maintaining mimm, but it would be fantastic to consolidate some common vision models there. I would be happy to point people to it as well!

**Comment by robertmccraith** [comment]
Feel free to submit an MR to mimm, I've had a few busy weeks but will be adding a few more models soon, possibly some detection, segmentation, VLMs, etc

**Comment by gboduljak** [comment]
Hi @robertmccraith :) I will submit a MR to `mimm` soon. Let me know if you need some help with adding more models.

**Pull request closed without merging**
