### PR TITLE
fix: string indentation with `textwrap.dedent`

### PR DESCRIPTION
**Pull request by sugatoray**
Use `textwrap.dedent` to allow proper indentation of strings.

**Current**

https://github.com/ml-explore/mlx-examples/blob/ae485633783a21204c74f97228fad251ac602e7b/llms/mlx_lm/utils.py#L440-L456 

**Suggested**:

```py
from textwrap import dedent

def somefunc():

	...

    text = dedent("""
        some text...
        goes here.

        ...
    """)

	...

```

### CODE REVIEW

**Comment by sugatoray** [comment]
cc: @awni

**Review by awni — APPROVED** [review]
Nice! Didn't know about that utility.

**Comment by awni** [comment]
Actually looks like the format failed. Do you mind running the pre commit hooks?

**Comment by sugatoray** [comment]
> Actually looks like the format failed. Do you mind running the pre commit hooks?

Ok. I will let you know once am done running it.

**Comment by sugatoray** [comment]
@awni I ran the pre-commit on the `utils.py` file and it passed from my end. Assuming that will be case for the CI as well.

image

**Review by awni — APPROVED** [review]
Looks good, thank you!

**Pull request merged**
