### PR TITLE
LoRA: support tools(function calling) format datasets

### PR DESCRIPTION
**Pull request by madroidmaq**
The dataset supports the tools field, with a structure definition consistent with OpenAI [fine-tuning](https://platform.openai.com/docs/guides/fine-tuning/fine-tuning-examples) and HuggingFace [chat_template](https://huggingface.co/docs/transformers/main/en/chat_templating), as follows:

- datasets 

```josn
{
    "messages": [
        { "role": "user", "content": "What is the weather in San Francisco?" },
        {
            "role": "assistant",
            "tool_calls": [
                {
                    "id": "call_id",
                    "type": "function",
                    "function": {
                        "name": "get_current_weather",
                        "arguments": "{\"location\": \"San Francisco, USA\", \"format\": \"celsius\"}"
                    }
                }
            ]
        }
    ],
    "tools": [
        {
            "type": "function",
            "function": {
                "name": "get_current_weather",
                "description": "Get the current weather",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "location": {
                            "type": "string",
                            "description": "The city and country, eg. San Francisco, USA"
                        },
                        "format": { "type": "string", "enum": ["celsius", "fahrenheit"] }
                    },
                    "required": ["location", "format"]
                }
            }
        }
    ]
}
```

- Qwen2.5(Qwen/Qwen2.5-0.5B-Instruct) Encode

```
<|im_start|>system
You are Qwen, created by Alibaba Cloud. You are a helpful assistant.

# Tools

You may call one or more functions to assist with the user query.

You are provided with function signatures within <tools></tools> XML tags:
<tools>
{"type": "function", "function": {"name": "get_current_weather", "description": "Get the current weather", "parameters": {"type": "object", "properties": {"location": {"type": "string", "description": "The city and country, eg. San Francisco, USA"}, "format": {"type": "string", "enum": ["celsius", "fahrenheit"]}}, "required": ["location", "format"]}}}
</tools>

For each function call, return a json object with function name and arguments within <tool_call></tool_call> XML tags:
<tool_call>
{"name": <function-name>, "arguments": <args-json-object>}
</tool_call><|im_end|>
<|im_start|>user
What is the weather in San Francisco?<|im_end|>
<|im_start|>assistant
```

Generation:

```
<tool_call>
{"name": "get_current_weather", "arguments": {"location": "San Francisco, USA", "format": "celsius"}}
</tool_call>
```

- Mistral(mistralai/Mistral-7B-Instruct-v0.3) Encode

```
<s>[AVAILABLE_TOOLS] [{"type": "function", "function": {"name": "get_current_weather", "description": "Get the current weather", "parameters": {"type": "object", "properties": {"location": {"type": "string", "description": "The city and country, eg. San Francisco, USA"}, "format": {"type": "string", "enum": ["celsius", "fahrenheit"]}}, "required": ["location", "format"]}}}][/AVAILABLE_TOOLS][INST] What is the weather in San Francisco?[/INST]
```

Generation:

```
[TOOL_CALLS] [{"name": "get_current_weather", "arguments": {"location": "San Francisco, USA", "format": "celsius"}}]
```

### CODE REVIEW

**Comment by madroidmaq** [comment]
@awni 
Many models have started supporting the Function Calling feature, and the [chat_template](https://huggingface.co/docs/transformers/main/en/chat_templating) in HuggingFace also supports this feature. So I added this PR, and I would like to know your thoughts on it and whether it can be merged.

**Comment by vlbosch** [comment]
Would be great to add function calling to MLX! That enables us to replace llama.cpp server with MLX in almost all scenarios. Does it automatically pick up the template from HF, or must every model be added manually?

**Review by awni — APPROVED** [review]
Nice addition, thank you 🙏

**Comment by madroidmaq** [comment]
> Would be great to add function calling to MLX! That enables us to replace llama.cpp server with MLX in almost all scenarios. Does it automatically pick up the template from HF, or must every model be added manually?

@alvarobartt It is automatically loaded from the basic model [chat_template](https://huggingface.co/docs/transformers/main/en/chat_templating). The loading method of each model may not be consistent (or not configured), as described above for Qwen2.5 It is not consistent with Mistral's configuration.

**Comment by alvarobartt** [comment]
Hi here @madroidmaq just flagging that I think you got the wrong mention? 😅

**Comment by madroidmaq** [comment]
> Hi here @madroidmaq just flagging that I think you got the wrong mention? 😅

Sorry, I mentioned the wrong person.

**Pull request merged**
