### PR TITLE
LoRA: Extract small function

### PR DESCRIPTION
**Pull request by madroidmaq**
Extract the `load_with_lora` function for easy use in other files.

### CODE REVIEW

**Comment by mzbac** [comment]
Maybe we should consider moving the function out of utils.py. It has becomed too large now,  it might be better to create a new file named `lora_utils.py` and place it there?

**Comment by madroidmaq** [comment]
@mzbac Great suggestion. Initially, I tried placing the `load_with_lora` function in both `tuner/lora.py` and `tuner/utils.py`, but encountered a circular dependency issue. When I attempted to resolve this issue, I found that it required significant changes. So, I ended up putting it in the `utils.py`.

I will reassess the extent of changes needed to solve the circular dependency problem. The worst-case scenario would be creating a new file named `tuner/lora_utils.py`, which I will try my best to avoid.

**Comment by awni** [comment]
@madroidmaq sorry for the delay! I think we can merge this. But could you first rebase to resolve conflicts?

**Comment by madroidmaq** [comment]
> @madroidmaq sorry for the delay! I think we can merge this. But could you first rebase to resolve conflicts?

It's DONE.

**Review by awni — APPROVED** [review]
Thanks!

**Pull request merged**
